jobs:
  test:
    name: Fast CI on Java ${{ matrix.java }} OS ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: ./mvnw -V --no-transfer-progress clean package
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8.0.345
        - 8
        - 11
        - 17
        - 20
        os:
        - ubuntu-latest
        - windows-latest
      max-parallel: 64
    timeout-minutes: 5
name: Fast CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
