jobs:
  test:
    name: CI by multiply java versions
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - continue-on-error: true
      name: Setup Java
      uses: actions/setup-java@v4
      with:
        cache: maven
        distribution: zulu
        java-version: '8

          8.0.345

          11

          17

          20

          '
    - continue-on-error: true
      name: Run integration test
      run: scripts/integration_test
    - continue-on-error: true
      name: Remove self maven install files
      run: rm -rf $HOME/.m2/repository/com/alibaba/dns-cache-manipulator*
    - continue-on-error: true
      name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}
    timeout-minutes: 10
name: Strong CI
on:
  repository_dispatch:
    types: trigger-ga___strong_ci.yaml
